### PR TITLE
Add form validation for job form #8

### PR DESCRIPTION
**Pull request by AjmalPonneth**

### CODE REVIEW

**Review by ayusshh19 — COMMENTED** [review]
Add validation for form fields with regex and raise invalid feedback for only that input which went wrong

**Comment by AjmalPonneth** [comment]
@ayusshh19 Now Iam added validation for required fields.

**Comment by ayusshh19** [comment]
> @ayusshh19 Now Iam added validation for required fields.

we want invalid feedback through not bootstrap

**Comment by ayusshh19** [comment]
> @ayusshh19 Now Iam added validation for required fields.

We want invalid feedback in javascript not in bootstrap

**Pull request closed without merging**
